FROM grafana/grafana:latest

LABEL author="Timo-Juhani Karjalainen, Cisco Systems"
LABEL description="TIG Stack Grafana image"

USER root
#COPY dashboards/dashboard.json /etc/grafana/dashboards/dashboard.json
COPY provisioning /etc/grafana/provisioning